// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorGreen': string;
  'colorYellow': string;
  'fullWidth': string;
  'root': string;
  'sizeMedium': string;
  'sizeSmall': string;
}
export const cssExports: CssExports;
export default cssExports;
