// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentText': string;
  'contentWrap': string;
  'h1': string;
  'home__parallax': string;
  'root': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
