// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  ExperienceValue: string;
  abilityValue: string;
  abilityWrap: string;
  bug: string;
  dark: string;
  dragon: string;
  electric: string;
  expProgress: string;
  experienceItem: string;
  fairy: string;
  fighting: string;
  fire: string;
  flying: string;
  generationValue: string;
  generationWrap: string;
  ghost: string;
  grass: string;
  ground: string;
  heathyPointsItem: string;
  heathyValue: string;
  helthyandexpWrap: string;
  hpProgress: string;
  ice: string;
  infoWrap: string;
  label: string;
  labelWrap: string;
  leftSide: string;
  namewrap: string;
  normal: string;
  pictureWrap: string;
  poison: string;
  psychic: string;
  regular: string;
  rightSide: string;
  rock: string;
  root: string;
  statItem: string;
  statValue: string;
  statWrap: string;
  stile: string;
  titleName: string;
  titleWrap: string;
  water: string;
}
export const cssExports: CssExports;
export default cssExports;
