// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ataqueSelect': string;
  'checkboxes': string;
  'closeCB': string;
  'openCB': string;
  'overSelect': string;
  'selectBox': string;
  'typeSelect': string;
}
export const cssExports: CssExports;
export default cssExports;
