// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'filterBlock': string;
  'loader': string;
  'loaderCardsBelowInput': string;
  'loaderTextAboveInput': string;
  'root': string;
  'rotating': string;
  'seachWrap': string;
  'searchInput': string;
}
export const cssExports: CssExports;
export default cssExports;
