// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'FromTo': string;
  'ataqueSelect': string;
  'checkboxes': string;
  'closeCB': string;
  'content': string;
  'filterBlock': string;
  'loader': string;
  'loaderCardsBelowInput': string;
  'loaderTextAboveInput': string;
  'openCB': string;
  'overSelect': string;
  'root': string;
  'seachWrap': string;
  'searchInput': string;
  'selectBox': string;
  'typeSelect': string;
}
export const cssExports: CssExports;
export default cssExports;
